name: Bump version

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v1
      - name: "Get email"
        run: |
          echo ::set-env name=GITHUB_EMAIL::$(git --no-pager show -s --format=\'%ae\')
      - name: "Get commit message"
        run: |
          echo ::set-env name=GITHUB_COMMIT_MESSAGE::$(git log -1 --pretty=%B)
      - name: "Setup GIT"
        run: |
          echo "Setting email to: ${GITHUB_EMAIL}"
          echo "Setting user to: ${GITHUB_ACTOR}"
          echo "Commit message: ${GITHUB_COMMIT_MESSAGE}"
          git config user.email "$GITHUB_EMAIL"
          git config user.name "$GITHUB_ACTOR"

      - name: "Checkout branch"
        run: |
          git checkout master

      - name: "Bump version"
        if: contains(env.GITHUB_COMMIT_MESSAGE, 'version bump to') == false
        run: |
          npm version patch -m "ci: version bump to v%s"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
